services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - '${PORT}:${PORT}'
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ./package.json
          action: rebuild
