services:
  backend:
    build: '.'
    container_name: backend
    ports:
      - '${APP_PORT}:${APP_PORT}'
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: ./package.json
          action: rebuild
